In [5]:
import numpy as np
import random

numbers = np.array([2, 3, 5, 7, 11])
twoDim = np.array([[2, 3, 5, 7, 11], [2, 3, 5, 7, 11]])
floats = np.array([1/i for i in range(1, 6)])

print(floats) # [1.         0.5        0.33333333 0.25       0.2       ]
print(type(numbers)) # <class 'numpy.ndarray'>
# Checking the type of the numpy array
print(numbers.dtype) #  dtype('int64'). printing will result to (int64)

# Get the number of dimensions
print(numbers.ndim) # 1
print(twoDim.ndim) # 2

# Get the shape of an array
print(numbers.shape) # (5,)
print(twoDim.shape) # (2, 5)

# Get the size of an array, which is the number of rows * the number of columns
print(numbers.size) # (5,) = 5 
print(twoDim.size) # (2, 5) = 10

# Get the amount of byte that is used to store an item in the array
print(numbers.itemsize) # 8
print(twoDim.itemsize) # 8

# Print the rows and columns in a two-dimensional array
for row in twoDim:
  for column in row:
    print(column, end=' ')
  print()
# Prints
# 2 3 5 7 11 
# 2 3 5 7 11

# flattening a multi-dimensional array into 1
for column in twoDim.flat:
  print(column, end=' ') # 2 3 5 7 11 2 3 5 7 11 

print('\n')

"""Filling arrays with specific values"""
zeros = np.zeros(5) #
print(zeros, end='\n') #[0. 0. 0. 0. 0.]

# with specific data types
ones = np.ones((2, 4), dtype=int)
print(ones, end='\n')
# [[1 1 1 1]
#  [1 1 1 1]]

values = np.full((3, 5), 13)
print(values, end='\n')
# [[13 13 13 13 13]
#  [13 13 13 13 13]
#  [13 13 13 13 13]]

"""Creating arrays from ranges"""
zero_to_five = np.arange(5)
print(zero_to_five, end='\n') # [0 1 2 3 4]
five_to_ten = np.arange(5, 10) # [5 6 7 8 9]
ten_to_one = np.arange(10, 1, -2) # [10, 8, 6, 4, 2]

# Creating a floating
floating_np = np.linspace(0.0, 1.0, num=10)
print(floating_np, end='\n') # [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556 0.66666667 0.77777778 0.88888889 1.        ]

# Creating a one-dimensional array and reshaping into n-dimensional array
reshape = np.arange(1, 21).reshape(4, 5)
print(reshape, end='\n')
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]
#  [11 12 13 14 15]
#  [16 17 18 19 20]]


# If you have more than 1000 elements to in n-dimensions, numpy will summarize the array rather than print all items
large_data = np.arange(1, 100001).reshape(4, 25000)
print(large_data, end='\n')
# [[     1      2      3 ...  24998  24999  25000]
#  [ 25001  25002  25003 ...  49998  49999  50000]
#  [ 50001  50002  50003 ...  74998  74999  75000]
#  [ 75001  75002  75003 ...  99998  99999 100000]]
another_large_data = np.arange(1, 100001).reshape(100, 1000)
print(another_large_data, end='\n')
# ...
#  [ 97001  97002  97003 ...  97998  97999  98000]
#  [ 98001  98002  98003 ...  98998  98999  99000]
#  [ 99001  99002  99003 ...  99998  99999 100000]]


"""Performance using ipython magic"""
%timeit rolls_list = [random.randrange(1, 7) for i in range(6_000_000)]
# 4.24 s ± 28.5 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit rolls_array = np.random.randint(1, 7, 6_000_000)
# 61.4 ms ± 419 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
%timeit rolls_array = np.random.randint(1, 7, 60_000_000)
# 793 ms ± 14.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit rolls_array = np.random.randint(1, 7, 600_000_000)
# 7.54 s ± 99.7 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
%timeit -n3 -r2 rolls_array = np.random.randint(1, 7, 6_000_000)
# 65.3 ms ± 7.66 ms per loop (mean ± std. dev. of 2 runs, 3 loops each)



[1.         0.5        0.33333333 0.25       0.2       ]
<class 'numpy.ndarray'>
int64
1
2
(5,)
(2, 5)
5
10
8
8
2 3 5 7 11 
2 3 5 7 11 
2 3 5 7 11 2 3 5 7 11 

[0. 0. 0. 0. 0.]
[[1 1 1 1]
 [1 1 1 1]]
[[13 13 13 13 13]
 [13 13 13 13 13]
 [13 13 13 13 13]]
[0 1 2 3 4]
[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[     1      2      3 ...  24998  24999  25000]
 [ 25001  25002  25003 ...  49998  49999  50000]
 [ 50001  50002  50003 ...  74998  74999  75000]
 [ 75001  75002  75003 ...  99998  99999 100000]]
[[     1      2      3 ...    998    999   1000]
 [  1001   1002   1003 ...   1998   1999   2000]
 [  2001   2002   2003 ...   2998   2999   3000]
 ...
 [ 97001  97002  97003 ...  97998  97999  98000]
 [ 98001  98002  98003 ...  98998  98999  99000]
 [ 99001  99002  99003 ...  99998  99999 100000]]
4.69 s ± 114 ms per loop (mean ± std. dev. of 7 ru